# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mer/Github/zstdtests

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mer/Github/zstdtests

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mer/Github/zstdtests/CMakeFiles /home/mer/Github/zstdtests//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mer/Github/zstdtests/CMakeFiles 0
.PHONY : all

# The main codegen target
codegen: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mer/Github/zstdtests/CMakeFiles /home/mer/Github/zstdtests//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 codegen
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mer/Github/zstdtests/CMakeFiles 0
.PHONY : codegen

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DisplayMgr

# Build rule for target.
DisplayMgr: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DisplayMgr
.PHONY : DisplayMgr

# fast build rule for target.
DisplayMgr/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayMgr.dir/build.make CMakeFiles/DisplayMgr.dir/build
.PHONY : DisplayMgr/fast

#=============================================================================
# Target rules for targets named Memory

# Build rule for target.
Memory: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Memory
.PHONY : Memory

# fast build rule for target.
Memory/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Memory.dir/build.make CMakeFiles/Memory.dir/build
.PHONY : Memory/fast

#=============================================================================
# Target rules for targets named PopenWindow

# Build rule for target.
PopenWindow: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 PopenWindow
.PHONY : PopenWindow

# fast build rule for target.
PopenWindow/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PopenWindow.dir/build.make CMakeFiles/PopenWindow.dir/build
.PHONY : PopenWindow/fast

#=============================================================================
# Target rules for targets named Print

# Build rule for target.
Print: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Print
.PHONY : Print

# fast build rule for target.
Print/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Print.dir/build.make CMakeFiles/Print.dir/build
.PHONY : Print/fast

#=============================================================================
# Target rules for targets named Routines

# Build rule for target.
Routines: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Routines
.PHONY : Routines

# fast build rule for target.
Routines/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Routines.dir/build.make CMakeFiles/Routines.dir/build
.PHONY : Routines/fast

#=============================================================================
# Target rules for targets named ThreadT

# Build rule for target.
ThreadT: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ThreadT
.PHONY : ThreadT

# fast build rule for target.
ThreadT/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThreadT.dir/build.make CMakeFiles/ThreadT.dir/build
.PHONY : ThreadT/fast

#=============================================================================
# Target rules for targets named Update

# Build rule for target.
Update: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Update
.PHONY : Update

# fast build rule for target.
Update/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Update.dir/build.make CMakeFiles/Update.dir/build
.PHONY : Update/fast

#=============================================================================
# Target rules for targets named siteTest

# Build rule for target.
siteTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 siteTest
.PHONY : siteTest

# fast build rule for target.
siteTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siteTest.dir/build.make CMakeFiles/siteTest.dir/build
.PHONY : siteTest/fast

#=============================================================================
# Target rules for targets named specsTest

# Build rule for target.
specsTest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 specsTest
.PHONY : specsTest

# fast build rule for target.
specsTest/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/specsTest.dir/build.make CMakeFiles/specsTest.dir/build
.PHONY : specsTest/fast

#=============================================================================
# Target rules for targets named zTests

# Build rule for target.
zTests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zTests
.PHONY : zTests

# fast build rule for target.
zTests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zTests.dir/build.make CMakeFiles/zTests.dir/build
.PHONY : zTests/fast

#=============================================================================
# Target rules for targets named zoobyBin

# Build rule for target.
zoobyBin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 zoobyBin
.PHONY : zoobyBin

# fast build rule for target.
zoobyBin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zoobyBin.dir/build.make CMakeFiles/zoobyBin.dir/build
.PHONY : zoobyBin/fast

Tests/DisplayMgr.o: Tests/DisplayMgr.c.o
.PHONY : Tests/DisplayMgr.o

# target to build an object file
Tests/DisplayMgr.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayMgr.dir/build.make CMakeFiles/DisplayMgr.dir/Tests/DisplayMgr.c.o
.PHONY : Tests/DisplayMgr.c.o

Tests/DisplayMgr.i: Tests/DisplayMgr.c.i
.PHONY : Tests/DisplayMgr.i

# target to preprocess a source file
Tests/DisplayMgr.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayMgr.dir/build.make CMakeFiles/DisplayMgr.dir/Tests/DisplayMgr.c.i
.PHONY : Tests/DisplayMgr.c.i

Tests/DisplayMgr.s: Tests/DisplayMgr.c.s
.PHONY : Tests/DisplayMgr.s

# target to generate assembly for a file
Tests/DisplayMgr.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DisplayMgr.dir/build.make CMakeFiles/DisplayMgr.dir/Tests/DisplayMgr.c.s
.PHONY : Tests/DisplayMgr.c.s

Tests/Memory.o: Tests/Memory.c.o
.PHONY : Tests/Memory.o

# target to build an object file
Tests/Memory.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Memory.dir/build.make CMakeFiles/Memory.dir/Tests/Memory.c.o
.PHONY : Tests/Memory.c.o

Tests/Memory.i: Tests/Memory.c.i
.PHONY : Tests/Memory.i

# target to preprocess a source file
Tests/Memory.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Memory.dir/build.make CMakeFiles/Memory.dir/Tests/Memory.c.i
.PHONY : Tests/Memory.c.i

Tests/Memory.s: Tests/Memory.c.s
.PHONY : Tests/Memory.s

# target to generate assembly for a file
Tests/Memory.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Memory.dir/build.make CMakeFiles/Memory.dir/Tests/Memory.c.s
.PHONY : Tests/Memory.c.s

Tests/PopenWindow.o: Tests/PopenWindow.c.o
.PHONY : Tests/PopenWindow.o

# target to build an object file
Tests/PopenWindow.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PopenWindow.dir/build.make CMakeFiles/PopenWindow.dir/Tests/PopenWindow.c.o
.PHONY : Tests/PopenWindow.c.o

Tests/PopenWindow.i: Tests/PopenWindow.c.i
.PHONY : Tests/PopenWindow.i

# target to preprocess a source file
Tests/PopenWindow.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PopenWindow.dir/build.make CMakeFiles/PopenWindow.dir/Tests/PopenWindow.c.i
.PHONY : Tests/PopenWindow.c.i

Tests/PopenWindow.s: Tests/PopenWindow.c.s
.PHONY : Tests/PopenWindow.s

# target to generate assembly for a file
Tests/PopenWindow.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/PopenWindow.dir/build.make CMakeFiles/PopenWindow.dir/Tests/PopenWindow.c.s
.PHONY : Tests/PopenWindow.c.s

Tests/Print.o: Tests/Print.c.o
.PHONY : Tests/Print.o

# target to build an object file
Tests/Print.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Print.dir/build.make CMakeFiles/Print.dir/Tests/Print.c.o
.PHONY : Tests/Print.c.o

Tests/Print.i: Tests/Print.c.i
.PHONY : Tests/Print.i

# target to preprocess a source file
Tests/Print.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Print.dir/build.make CMakeFiles/Print.dir/Tests/Print.c.i
.PHONY : Tests/Print.c.i

Tests/Print.s: Tests/Print.c.s
.PHONY : Tests/Print.s

# target to generate assembly for a file
Tests/Print.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Print.dir/build.make CMakeFiles/Print.dir/Tests/Print.c.s
.PHONY : Tests/Print.c.s

Tests/Routines.o: Tests/Routines.c.o
.PHONY : Tests/Routines.o

# target to build an object file
Tests/Routines.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Routines.dir/build.make CMakeFiles/Routines.dir/Tests/Routines.c.o
.PHONY : Tests/Routines.c.o

Tests/Routines.i: Tests/Routines.c.i
.PHONY : Tests/Routines.i

# target to preprocess a source file
Tests/Routines.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Routines.dir/build.make CMakeFiles/Routines.dir/Tests/Routines.c.i
.PHONY : Tests/Routines.c.i

Tests/Routines.s: Tests/Routines.c.s
.PHONY : Tests/Routines.s

# target to generate assembly for a file
Tests/Routines.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Routines.dir/build.make CMakeFiles/Routines.dir/Tests/Routines.c.s
.PHONY : Tests/Routines.c.s

Tests/ThreadT.o: Tests/ThreadT.c.o
.PHONY : Tests/ThreadT.o

# target to build an object file
Tests/ThreadT.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThreadT.dir/build.make CMakeFiles/ThreadT.dir/Tests/ThreadT.c.o
.PHONY : Tests/ThreadT.c.o

Tests/ThreadT.i: Tests/ThreadT.c.i
.PHONY : Tests/ThreadT.i

# target to preprocess a source file
Tests/ThreadT.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThreadT.dir/build.make CMakeFiles/ThreadT.dir/Tests/ThreadT.c.i
.PHONY : Tests/ThreadT.c.i

Tests/ThreadT.s: Tests/ThreadT.c.s
.PHONY : Tests/ThreadT.s

# target to generate assembly for a file
Tests/ThreadT.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ThreadT.dir/build.make CMakeFiles/ThreadT.dir/Tests/ThreadT.c.s
.PHONY : Tests/ThreadT.c.s

Tests/Update.o: Tests/Update.c.o
.PHONY : Tests/Update.o

# target to build an object file
Tests/Update.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Update.dir/build.make CMakeFiles/Update.dir/Tests/Update.c.o
.PHONY : Tests/Update.c.o

Tests/Update.i: Tests/Update.c.i
.PHONY : Tests/Update.i

# target to preprocess a source file
Tests/Update.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Update.dir/build.make CMakeFiles/Update.dir/Tests/Update.c.i
.PHONY : Tests/Update.c.i

Tests/Update.s: Tests/Update.c.s
.PHONY : Tests/Update.s

# target to generate assembly for a file
Tests/Update.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Update.dir/build.make CMakeFiles/Update.dir/Tests/Update.c.s
.PHONY : Tests/Update.c.s

Tests/siteTest.o: Tests/siteTest.c.o
.PHONY : Tests/siteTest.o

# target to build an object file
Tests/siteTest.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siteTest.dir/build.make CMakeFiles/siteTest.dir/Tests/siteTest.c.o
.PHONY : Tests/siteTest.c.o

Tests/siteTest.i: Tests/siteTest.c.i
.PHONY : Tests/siteTest.i

# target to preprocess a source file
Tests/siteTest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siteTest.dir/build.make CMakeFiles/siteTest.dir/Tests/siteTest.c.i
.PHONY : Tests/siteTest.c.i

Tests/siteTest.s: Tests/siteTest.c.s
.PHONY : Tests/siteTest.s

# target to generate assembly for a file
Tests/siteTest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/siteTest.dir/build.make CMakeFiles/siteTest.dir/Tests/siteTest.c.s
.PHONY : Tests/siteTest.c.s

Tests/specsTest.o: Tests/specsTest.c.o
.PHONY : Tests/specsTest.o

# target to build an object file
Tests/specsTest.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/specsTest.dir/build.make CMakeFiles/specsTest.dir/Tests/specsTest.c.o
.PHONY : Tests/specsTest.c.o

Tests/specsTest.i: Tests/specsTest.c.i
.PHONY : Tests/specsTest.i

# target to preprocess a source file
Tests/specsTest.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/specsTest.dir/build.make CMakeFiles/specsTest.dir/Tests/specsTest.c.i
.PHONY : Tests/specsTest.c.i

Tests/specsTest.s: Tests/specsTest.c.s
.PHONY : Tests/specsTest.s

# target to generate assembly for a file
Tests/specsTest.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/specsTest.dir/build.make CMakeFiles/specsTest.dir/Tests/specsTest.c.s
.PHONY : Tests/specsTest.c.s

Tests/zTests.o: Tests/zTests.c.o
.PHONY : Tests/zTests.o

# target to build an object file
Tests/zTests.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zTests.dir/build.make CMakeFiles/zTests.dir/Tests/zTests.c.o
.PHONY : Tests/zTests.c.o

Tests/zTests.i: Tests/zTests.c.i
.PHONY : Tests/zTests.i

# target to preprocess a source file
Tests/zTests.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zTests.dir/build.make CMakeFiles/zTests.dir/Tests/zTests.c.i
.PHONY : Tests/zTests.c.i

Tests/zTests.s: Tests/zTests.c.s
.PHONY : Tests/zTests.s

# target to generate assembly for a file
Tests/zTests.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zTests.dir/build.make CMakeFiles/zTests.dir/Tests/zTests.c.s
.PHONY : Tests/zTests.c.s

Tests/zoobyBin.o: Tests/zoobyBin.c.o
.PHONY : Tests/zoobyBin.o

# target to build an object file
Tests/zoobyBin.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zoobyBin.dir/build.make CMakeFiles/zoobyBin.dir/Tests/zoobyBin.c.o
.PHONY : Tests/zoobyBin.c.o

Tests/zoobyBin.i: Tests/zoobyBin.c.i
.PHONY : Tests/zoobyBin.i

# target to preprocess a source file
Tests/zoobyBin.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zoobyBin.dir/build.make CMakeFiles/zoobyBin.dir/Tests/zoobyBin.c.i
.PHONY : Tests/zoobyBin.c.i

Tests/zoobyBin.s: Tests/zoobyBin.c.s
.PHONY : Tests/zoobyBin.s

# target to generate assembly for a file
Tests/zoobyBin.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/zoobyBin.dir/build.make CMakeFiles/zoobyBin.dir/Tests/zoobyBin.c.s
.PHONY : Tests/zoobyBin.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... codegen"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DisplayMgr"
	@echo "... Memory"
	@echo "... PopenWindow"
	@echo "... Print"
	@echo "... Routines"
	@echo "... ThreadT"
	@echo "... Update"
	@echo "... siteTest"
	@echo "... specsTest"
	@echo "... zTests"
	@echo "... zoobyBin"
	@echo "... Tests/DisplayMgr.o"
	@echo "... Tests/DisplayMgr.i"
	@echo "... Tests/DisplayMgr.s"
	@echo "... Tests/Memory.o"
	@echo "... Tests/Memory.i"
	@echo "... Tests/Memory.s"
	@echo "... Tests/PopenWindow.o"
	@echo "... Tests/PopenWindow.i"
	@echo "... Tests/PopenWindow.s"
	@echo "... Tests/Print.o"
	@echo "... Tests/Print.i"
	@echo "... Tests/Print.s"
	@echo "... Tests/Routines.o"
	@echo "... Tests/Routines.i"
	@echo "... Tests/Routines.s"
	@echo "... Tests/ThreadT.o"
	@echo "... Tests/ThreadT.i"
	@echo "... Tests/ThreadT.s"
	@echo "... Tests/Update.o"
	@echo "... Tests/Update.i"
	@echo "... Tests/Update.s"
	@echo "... Tests/siteTest.o"
	@echo "... Tests/siteTest.i"
	@echo "... Tests/siteTest.s"
	@echo "... Tests/specsTest.o"
	@echo "... Tests/specsTest.i"
	@echo "... Tests/specsTest.s"
	@echo "... Tests/zTests.o"
	@echo "... Tests/zTests.i"
	@echo "... Tests/zTests.s"
	@echo "... Tests/zoobyBin.o"
	@echo "... Tests/zoobyBin.i"
	@echo "... Tests/zoobyBin.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

